# Arquivo de configuração para o pre-commit.
# Define os "hooks" (verificações) que serão executados antes de cada commit.

repos:
  # Hooks padrão para limpeza de arquivos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace         # Remove espaços em branco no final das linhas
      - id: end-of-file-fixer          # Garante que os arquivos terminem com uma nova linha
      - id: check-yaml                 # Verifica a sintaxe de arquivos YAML
      - id: check-json                 # Verifica a sintaxe de arquivos JSON
      - id: check-added-large-files    # Impede que arquivos grandes sejam commitados

  # Hook para o Black (Formatador)
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # Hook para o iSort (Organizador de Imports)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # Hook para o Flake8 (Linter de Estilo e Erros)
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-import-order
          - flake8-docstrings
          - flake8-bugbear

  # Hook para o MyPy (Verificador de Tipos Estáticos)
  # Nota: pode ser um pouco lento para rodar.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

  # Hook para o Hadolint (Linter de Dockerfile)
  # Responde à sua pergunta sobre lint para o Docker!
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: ["--ignore", "DL3013"] # Exemplo de como ignorar uma regra específica
